name = "sweep-affiliate-claim"
main = "affiliate-claim-worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "CLAIM_STATE", id = "716bb15f18aa48e7a0a483c4467ffcd2" },
  { binding = "RECEIPTS", id = "2cda434a2d7043a78213fa9c1ae21f9e" }
]

[triggers]
crons = ["0 3 * * *"]